# Generated by Django 5.0.7 on 2024-12-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('instrument_type', models.CharField(choices=[('piano', 'Piano'), ('drumno', 'Drum'), ('violin', 'Violin'), ('flute', 'Flute'), ('guitat', 'Guitat')], max_length=200)),
            ],
        ),
    ]
