# Generated by Django 5.0.7 on 2024-12-27 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
        ),
    ]
