# Generated by Django 5.0.7 on 2024-12-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('instrument_type', models.CharField(choices=[('1star', '1-star'), ('2star', '2-star'), ('3star', '3-star'), ('4star', '4-star'), ('5star', '5-star')], max_length=200)),
            ],
        ),
    ]
