# Generated by Django 5.0.7 on 2024-12-27 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_release_date'),
        ('musicians', '0003_remove_musician_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicians.musician'),
        ),
    ]
