# Generated by Django 5.0.7 on 2024-12-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('posts', '0003_remove_post_author'),
        ('profiles', '0003_remove_profile_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
